domains:
  - domain: "https://yourDomain.com/"
    service_account: "config/service-accounts/website1-service-account.json"
    sitemap_url: "https://yourDomain.com/sitemap.xml"
    daily_quota: 200

